spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_movie_night?useSSL=false
    username: root
    password: adgjmptx
    platform: mysql
  session:
    store-type: jdbc
server:
  port: 80
  ssl:
    key-store: keystore.p12
    key-store-password: "#Adgjmptx1313"
