spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_movie_night?useSSL=false
    username: user
    password: password
    platform: mysql
  session:
    store-type: jdbc
server:
  port: 8001
